## Goal

is to implement and refresh the multivariate concepts.

**Note** allowed to use *numpy and scipy* to complete the tasks.

**So Lets Start**

In [131]:
# magic command to include all the necessary libraries
%pylab inline 

Populating the interactive namespace from numpy and matplotlib


`%matplotlib` prevents importing * from pylab and numpy


In [132]:
#Download the IRIS dataset
#"!" means run the bash (shell) command
!wget http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data

--2017-02-22 18:59:40--  http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.249
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.249|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4551 (4.4K) [text/plain]
Saving to: ‘iris.data.1’

iris.data.1         100%[===================>]   4.44K  --.-KB/s    in 0.01s   

2017-02-22 18:59:41 (377 KB/s) - ‘iris.data.1’ saved [4551/4551]



In [133]:
#import pandas and name this namespace as pd
import pandas as pd

In [134]:
#Load data and name the columns
data=pd.read_csv('iris.data')
data.columns=['SepalLength','SepalWidth','PetalLength','PetalWidth','Class']
print data.describe()

       SepalLength  SepalWidth  PetalLength  PetalWidth
count   149.000000  149.000000   149.000000  149.000000
mean      5.848322    3.051007     3.774497    1.205369
std       0.828594    0.433499     1.759651    0.761292
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.400000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000


In [135]:
#Code for generating data....
datalist=[] #create an empty list
# data list is a list of two elements, where index=0 contains data corresponding to petal 
# length and index=1 contains data corresponding to petal width
datalist.append(list(data['PetalLength'].dropna()))
datalist.append(list(data['PetalWidth'].dropna()))
datalist.append(list(data['SepalLength'].dropna()))
datalist.append(list(data['SepalWidth'].dropna()))

classlist=[] #create an empty list
# data list is a list of two elements, where index=0 contains data corresponding to petal 
# length and index=1 contains data corresponding to petal width
classlist.append(list(data['PetalLength'].dropna()))
classlist.append(list(data['PetalWidth'].dropna()))
classlist.append(list(data['SepalLength'].dropna()))
classlist.append(list(data['SepalWidth'].dropna()))
classlist.append(list(data['Class'].dropna()))

#If you want you build a numpy array from this list.


print "PetalLength=", datalist[0]
print "PetalWidth=", datalist[1]

#This and above code are both same...
# datalist=[0]*2#create a list of 2 elements
# datalist[0]=(list(data['PetalLength'].dropna()))
# datalist[1]=(list(data['PetalWidth'].dropna()))
#data list is a list of two elements, where index=0 contains data corresponding to petal 
# length and index=1 contains data corresponding to petal width
# print("PetalLength=", datalist[0])
# print("PetalWidth=", datalist[1])

PetalLength= [1.3999999999999999, 1.3, 1.5, 1.3999999999999999, 1.7, 1.3999999999999999, 1.5, 1.3999999999999999, 1.5, 1.5, 1.6000000000000001, 1.3999999999999999, 1.1000000000000001, 1.2, 1.5, 1.3, 1.3999999999999999, 1.7, 1.5, 1.7, 1.5, 1.0, 1.7, 1.8999999999999999, 1.6000000000000001, 1.6000000000000001, 1.5, 1.3999999999999999, 1.6000000000000001, 1.6000000000000001, 1.5, 1.5, 1.3999999999999999, 1.5, 1.2, 1.3, 1.5, 1.3, 1.5, 1.3, 1.3, 1.3, 1.6000000000000001, 1.8999999999999999, 1.3999999999999999, 1.6000000000000001, 1.3999999999999999, 1.5, 1.3999999999999999, 4.7000000000000002, 4.5, 4.9000000000000004, 4.0, 4.5999999999999996, 4.5, 4.7000000000000002, 3.2999999999999998, 4.5999999999999996, 3.8999999999999999, 3.5, 4.2000000000000002, 4.0, 4.7000000000000002, 3.6000000000000001, 4.4000000000000004, 4.5, 4.0999999999999996, 4.5, 3.8999999999999999, 4.7999999999999998, 4.0, 4.9000000000000004, 4.7000000000000002, 4.2999999999999998, 4.4000000000000004, 4.7999999999999998, 5.0, 4

*In all the tasks given below use the list variable `datalist` (defined above) to answer all the questions.*

#### Task1
----------------
Lets model the petal length and width as continuous random variable $X=(x_1,x_2)$. Find the empirical mean of this random variable. Here $x_1$ specifies the petal length and $x_2$ its width.

In [136]:
#Write your code here
data= np.array(datalist).T
print data[:,0:2]
print 'mean:', np.mean(data,axis=0)

[[ 1.4  0.2]
 [ 1.3  0.2]
 [ 1.5  0.2]
 [ 1.4  0.2]
 [ 1.7  0.4]
 [ 1.4  0.3]
 [ 1.5  0.2]
 [ 1.4  0.2]
 [ 1.5  0.1]
 [ 1.5  0.2]
 [ 1.6  0.2]
 [ 1.4  0.1]
 [ 1.1  0.1]
 [ 1.2  0.2]
 [ 1.5  0.4]
 [ 1.3  0.4]
 [ 1.4  0.3]
 [ 1.7  0.3]
 [ 1.5  0.3]
 [ 1.7  0.2]
 [ 1.5  0.4]
 [ 1.   0.2]
 [ 1.7  0.5]
 [ 1.9  0.2]
 [ 1.6  0.2]
 [ 1.6  0.4]
 [ 1.5  0.2]
 [ 1.4  0.2]
 [ 1.6  0.2]
 [ 1.6  0.2]
 [ 1.5  0.4]
 [ 1.5  0.1]
 [ 1.4  0.2]
 [ 1.5  0.1]
 [ 1.2  0.2]
 [ 1.3  0.2]
 [ 1.5  0.1]
 [ 1.3  0.2]
 [ 1.5  0.2]
 [ 1.3  0.3]
 [ 1.3  0.3]
 [ 1.3  0.2]
 [ 1.6  0.6]
 [ 1.9  0.4]
 [ 1.4  0.3]
 [ 1.6  0.2]
 [ 1.4  0.2]
 [ 1.5  0.2]
 [ 1.4  0.2]
 [ 4.7  1.4]
 [ 4.5  1.5]
 [ 4.9  1.5]
 [ 4.   1.3]
 [ 4.6  1.5]
 [ 4.5  1.3]
 [ 4.7  1.6]
 [ 3.3  1. ]
 [ 4.6  1.3]
 [ 3.9  1.4]
 [ 3.5  1. ]
 [ 4.2  1.5]
 [ 4.   1. ]
 [ 4.7  1.4]
 [ 3.6  1.3]
 [ 4.4  1.4]
 [ 4.5  1.5]
 [ 4.1  1. ]
 [ 4.5  1.5]
 [ 3.9  1.1]
 [ 4.8  1.8]
 [ 4.   1.3]
 [ 4.9  1.5]
 [ 4.7  1.2]
 [ 4.3  1.3]
 [ 4.4  1.4]
 [ 4.8  1.4]
 [ 5.   1.7]

#### Task2
----------------
Compute the covariance matrix $X$ using outper product formula, i.e. $\Sigma=\frac{1}{n}Z^T\;Z$, where $Z$ is centered data matrix (mean = 0)

In [137]:
#Write your code here
Z= np.array(datalist)
Z=Z.T
m= np.mean(Z,axis=0)
Z= Z - m
n=Z.shape[0]

sigma= (float(1)/n) * np.dot(Z.T,Z)

print'covariance for all features: ' 
print sigma
print 
print 

X= Z[:,0:2]
m=np.mean(X,axis=0)
X=X-m
sigma= (float(1)/n) * np.dot(X.T,X)
print'covariance for petal length and width: '
print sigma


covariance for all features: 
[[ 3.07559119  1.2804725   1.2618364  -0.3146052 ]
 [ 1.2804725   0.57567587  0.5118882  -0.11497185]
 [ 1.2618364   0.5118882   0.68196027 -0.03702851]
 [-0.3146052  -0.11497185 -0.03702851  0.18666006]]


covariance for petal length and width: 
[[ 3.07559119  1.2804725 ]
 [ 1.2804725   0.57567587]]


#### Task3: Multivariate Gaussian
----------------
Let's model $X$ with multivariate Gaussian. Find the probability of having flowers with petal width and height in the following range $P(3.5 < x_1 < 3.7,5.5 < x_2 <5.6)$.
Recall that 
$$f_{\mathbf x}(x_1,\ldots,x_k) = \frac{1}{\sqrt{(2\pi)^k|\boldsymbol\Sigma|}} \exp\left(-\frac{1}{2}({\mathbf x}-{\boldsymbol\mu})^\mathrm{T}{\boldsymbol\Sigma}^{-1}({\mathbf x}-{\boldsymbol\mu}) \right)$$

where ${\mathbf x}$ is a real k-dimensional column vector and $|\boldsymbol\Sigma|$ is the determinant of $\boldsymbol\Sigma$. For our this case $k=2$ 

In [138]:
#Write your code here, you are not allowed to use scipy and numpy function here... 
import math
    
sigdet= (sigma[0,0]*sigma[0,0] - sigma[1,0]*sigma[0,1])

area=0
for x in arange(3.5,3.7,0.01):
    for y in arange(5.5,5.6,0.01):
        t=np.array([y, x])
        temp= 1/(((2*math.pi)**2) * sigdet)** 0.5
        ex=math.exp(-0.5*np.dot(np.dot( (t-m).T , inv(sigma) ) ,t-m ))
        f=temp*ex
        area+=0.01*f

print 'Prob: ', area
        

Prob:  9.17308727449e-12


In [139]:
#Now go and use the function to find the pdf value and compares these newly computed value
#with the earlier value and compute the difference...
scipy.stats.multivariate_normal()

#### Task4: Multivariate Gaussian

Now consider that both the attributes are statistically independent and normally distributed then what will be the probability of $P(3.5 < x_1 < 3.7,5.5 < x_2 <5.6)$


In [140]:
import scipy.stats
s= np.std(X,axis=0) #stddev
scipy.stats.norm(m,s).pdf(X)

array([[ 0.0909635 ,  0.21855244],
       [ 0.08406817,  0.21855244],
       [ 0.09810489,  0.21855244],
       [ 0.0909635 ,  0.21855244],
       [ 0.11300597,  0.29933618],
       [ 0.0909635 ,  0.2580058 ],
       [ 0.09810489,  0.21855244],
       [ 0.0909635 ,  0.21855244],
       [ 0.09810489,  0.18194402],
       [ 0.09810489,  0.21855244],
       [ 0.10546347,  0.21855244],
       [ 0.0909635 ,  0.18194402],
       [ 0.07110896,  0.18194402],
       [ 0.07744333,  0.21855244],
       [ 0.09810489,  0.29933618],
       [ 0.08406817,  0.29933618],
       [ 0.0909635 ,  0.2580058 ],
       [ 0.11300597,  0.2580058 ],
       [ 0.09810489,  0.2580058 ],
       [ 0.11300597,  0.21855244],
       [ 0.09810489,  0.29933618],
       [ 0.06508075,  0.21855244],
       [ 0.11300597,  0.34130674],
       [ 0.12848839,  0.21855244],
       [ 0.10546347,  0.21855244],
       [ 0.10546347,  0.29933618],
       [ 0.09810489,  0.21855244],
       [ 0.0909635 ,  0.21855244],
       [ 0.10546347,

#### Task5: Categorical Random Variables.
----------------
Lets categorize the petal length variable to four categories, i.e very short $\in[1,1.6]$, short $\in(1.6,4.4]$, long $\in(4.4,5.1]$, very long $\in(5.1,6.9]$ and model this varible using random variable $x$

Find the probability of this cateogrical random variable.

In [141]:
#Write your code here
petal_length= np.array(datalist[0]).T
total= np.size(petal_length)
pl_class= np.zeros((total,4))

pl_class[:,0]= (petal_length>=1) & (petal_length<=1.6)
pl_class[:,1]= (petal_length>1.6) & (petal_length<=4.4)
pl_class[:,2]= (petal_length>4.4) & (petal_length<=5.1)
pl_class[:,3]= (petal_length>5.1) & (petal_length<=6.9)

print 'Total: ', total
print 'flowers in each category:\n'
print ' VS    S    L    VL' 
print np.sum(pl_class,axis=0)
print
print 'Probabilities: \n'
print 'very short      short        long       very long'
print np.sum(pl_class,axis=0)/float(total)

Total:  149
flowers in each category:

 VS    S    L    VL
[ 43.  35.  37.  34.]

Probabilities: 

very short      short        long       very long
[ 0.2885906   0.23489933  0.24832215  0.22818792]


#### Task6: Categorical Random Variables.
Find the mean and covariance matrix of categorical variable $x$.

In [142]:
#Write your code here
m=np.mean(pl_class,axis=0)
print 'mean: ', m
print 'Covarinace Matrix: '
print (1/float(total)) * np.dot((pl_class-m).T, (pl_class-m))

mean:  [ 0.2885906   0.23489933  0.24832215  0.22818792]
Covarinace Matrix: 
[[ 0.20530607 -0.06778974 -0.07166344 -0.06585289]
 [-0.06778974  0.17972163 -0.05833071 -0.05360119]
 [-0.07166344 -0.05833071  0.18665826 -0.05666411]
 [-0.06585289 -0.05360119 -0.05666411  0.17611819]]


#### Task7: Categorical Random Variables.

If we select 10 random flowers what will be the probability of picking 3 very short length, 2 short length, 4 long length and 1 very long petal length flowers.

In [143]:
#Write your code here
p= (math.factorial(10)/(math.factorial(3)*math.factorial(2)*math.factorial(4)*math.factorial(1)))* np.product(m**[3, 2,  4,  1])
print 'prob: ', p

prob:  0.0144989025118


#### Task8: Bivariate Categorical Random Variables.
----------------
Lets also categorize the petal width variable to three categories, i.e short $\in[0.1,1.0]$, medium  $\in(1.0,1.75)$, long $\in(1.75,2.5]$.

Now lets model both the petal length and width as bivariate categorical random variable $X$.
Find the probability for following cases.

$$p(x_1=[1000], x_2=[000])$$
$$p(x_1=[1000], x_2=[001])$$

$$p(x_1=[0010], x_2=[010])$$
$$p(x_1=[0001], x_2=[100])$$


In [151]:
#Write your code here
petal_width= np.array(datalist[1]).T
total= np.size(petal_width)
pw_class= np.zeros((total,3))

pw_class[:,0]= (petal_width>=0.1) & (petal_width<=1.0)
pw_class[:,1]= (petal_width>1.0) & (petal_width<=1.75)
pw_class[:,2]= (petal_width>1.75) & (petal_width<=2.5)
print 'Probabilities:'
print '  short          medium       long'
print np.sum(pw_class,axis=0)/float(total)

print 'p(x1=[1000],x2=[100]):'+ str(np.sum((pl_class[:,0]==1) & (pw_class[:,0]==1))/float(total))
print 'p(x1=[1000],x2=[001]):'+ str(np.sum((pl_class[:,0]==1) & (pw_class[:,2]==1))/float(total))
print 'p(x1=[0010],x2=[010]):'+ str(np.sum((pl_class[:,2]==1) & (pw_class[:,1]==1))/float(total))
print 'p(x1=[0001],x2=[100]):'+ str(np.sum((pl_class[:,3]==1) & (pw_class[:,0]==1))/float(total))

Probabilities:
  short          medium       long
[ 0.37583893  0.31543624  0.30872483]
p(x1=[1000],x2=[100]):0.288590604027
p(x1=[1000],x2=[001]):0.0
p(x1=[0010],x2=[010]):0.154362416107
p(x1=[0001],x2=[100]):0.0


#### Task9: Normalization
----------------
Normalize both the attributes (petal length and petal width) such that after normalization their values must lie in the interval [-2, 5]

In [145]:
#Write your code here
petal_data= np.array(datalist).T
petal_data= petal_data[:,0:2]
unit_norm_data= (petal_data- np.min(petal_data))/ (np.max(petal_data) - np.min(petal_data))
print (unit_norm_data* 7)-2 

[[-0.66176471 -1.89705882]
 [-0.76470588 -1.89705882]
 [-0.55882353 -1.89705882]
 [-0.66176471 -1.89705882]
 [-0.35294118 -1.69117647]
 [-0.66176471 -1.79411765]
 [-0.55882353 -1.89705882]
 [-0.66176471 -1.89705882]
 [-0.55882353 -2.        ]
 [-0.55882353 -1.89705882]
 [-0.45588235 -1.89705882]
 [-0.66176471 -2.        ]
 [-0.97058824 -2.        ]
 [-0.86764706 -1.89705882]
 [-0.55882353 -1.69117647]
 [-0.76470588 -1.69117647]
 [-0.66176471 -1.79411765]
 [-0.35294118 -1.79411765]
 [-0.55882353 -1.79411765]
 [-0.35294118 -1.89705882]
 [-0.55882353 -1.69117647]
 [-1.07352941 -1.89705882]
 [-0.35294118 -1.58823529]
 [-0.14705882 -1.89705882]
 [-0.45588235 -1.89705882]
 [-0.45588235 -1.69117647]
 [-0.55882353 -1.89705882]
 [-0.66176471 -1.89705882]
 [-0.45588235 -1.89705882]
 [-0.45588235 -1.89705882]
 [-0.55882353 -1.69117647]
 [-0.55882353 -2.        ]
 [-0.66176471 -1.89705882]
 [-0.55882353 -2.        ]
 [-0.86764706 -1.89705882]
 [-0.76470588 -1.89705882]
 [-0.55882353 -2.        ]
 

#### Task10: Class wise mean vector and covariance matrix...
Iris dataset have three different classes, now go and compute the class-wise (setosa, versicolor and virginica) mean vector and covariance matrix.

In [146]:
#Write your code here
data= np.array(datalist).T
cdata= np.array(classlist).T
setosa= data[cdata[:,4]== 'Iris-setosa']
versicolor= data[cdata[:,4]== 'Iris-versicolor']
virginica= data[cdata[:,4]== 'Iris-virginica']
setosa_mean= np.mean(setosa,axis=0)
X= setosa - setosa_mean
total= setosa.shape[0]
setosa_cov= (1/ float(total)) * np.dot(X.T,X)
print 'Iris-setosa Mean: '
print setosa_mean
print 'Iris-setosa covariance: '
print setosa_cov
print 

versicolor_mean= np.mean(versicolor,axis=0)
X= versicolor - versicolor_mean
total= versicolor.shape[0]
versicolor_cov= (1/ float(total)) * np.dot(X.T,X)
print 'Iris-versicolor Mean: '
print versicolor_mean
print 'Iris-versicolor covariance: '
print versicolor_cov
print 

virginica_mean= np.mean(virginica,axis=0)
X= virginica - virginica_mean
total= virginica.shape[0]
virginica_cov= (1/ float(total)) * np.dot(X.T,X)
print 'Iris-virginica Mean: '
print virginica_mean
print 'Iris-virginica covariance: '
print virginica_cov


Iris-setosa Mean: 
[ 1.46530612  0.24489796  5.00408163  3.41632653]
Iris-setosa covariance: 
[[ 0.03002082  0.00563932  0.01626406  0.01179092]
 [ 0.00563932  0.01145356  0.01063307  0.01151187]
 [ 0.01626406  0.01063307  0.12406497  0.10013744]
 [ 0.01179092  0.01151187  0.10013744  0.14503957]]

Iris-versicolor Mean: 
[ 4.26   1.326  5.936  2.77 ]
Iris-versicolor covariance: 
[[ 0.2164    0.07164   0.17924   0.081   ]
 [ 0.07164   0.038324  0.054664  0.04038 ]
 [ 0.17924   0.054664  0.261104  0.08348 ]
 [ 0.081     0.04038   0.08348   0.0965  ]]

Iris-virginica Mean: 
[ 5.552  2.026  6.588  2.974]
Iris-virginica covariance: 
[[ 0.298496  0.047848  0.297224  0.069952]
 [ 0.047848  0.073924  0.048112  0.046676]
 [ 0.297224  0.048112  0.396256  0.091888]
 [ 0.069952  0.046676  0.091888  0.101924]]


#### Task11: Caclulating the Probability of a flower belonging to a particular class
Using above information, lets model each class to be modeled by continuous multivariate Gaussian Random varible. Now we have recorded a flower with following attributes (sepal lenght=4, petal length=6, sepal width=4, sepal length=5.5) in the field, which class it belongs. 

In [147]:
#Write your code here

#supposing k=2
epsilon= 0.01
setosa_det= (setosa_cov[0,0]*setosa_cov[1,1]) - (setosa_cov[0,1] * setosa_cov[1,0])
temp= 1/(((2*math.pi)**2) * setosa_det)** 0.5
exp=math.exp(-0.5*np.dot(np.dot( ([4, 6 , 4, 5.5]-setosa_mean).T , inv(setosa_cov) ) ,[4, 6 , 4, 5.5]-setosa_mean))
guassain_setosa= 2*temp*epsilon*exp 
print 'setosa probability: ', guassain_setosa

versicolor_det= (versicolor_cov[0,0]*versicolor_cov[1,1]) - (versicolor_cov[0,1] * versicolor_cov[1,0])
temp= 1/(((2*math.pi)**2) * versicolor_det)** 0.5
exp=math.exp(-0.5*np.dot(np.dot( ([4, 6 , 4, 5.5]-versicolor_mean).T , inv(versicolor_cov) ) ,[4, 6 , 4, 5.5]-versicolor_mean))
guassain_versicolor= 2*temp*epsilon*exp 
print 'versicolor probability: ', guassain_versicolor

virginica_det= (virginica_cov[0,0]*virginica_cov[1,1]) - (virginica_cov[0,1] * virginica_cov[1,0])
temp= 1/(((2*math.pi)**2) * virginica_det)** 0.5
exp=math.exp(-0.5*np.dot(np.dot( ([4, 6 , 4, 5.5]-virginica_mean).T , inv(virginica_cov) ) ,[4, 6 , 4, 5.5]-virginica_mean))
guassain_virginica= 2*temp*epsilon*exp 
print 'virginica probability: ', guassain_virginica

print "It belongs to virginica class due to highest probability"

setosa probability:  0.0
versicolor probability:  0.0
virginica probability:  1.09546635313e-67
It belongs to virginica class due to highest probability



#### Task12:  X is a normally distributed variable with mean μ = 30 and standard deviation σ = 4. Find 

a) P(x < 40)

b) P(x > 21)

c) P(30 < x < 35)

You can use scipy.stats.norm functions to answer these questions. These problems are contributed by an anonymous source.

In [148]:
#Write your code here
print 'P(x < 40): '+str(scipy.stats.norm(30,4).cdf(40))
print 'P(x > 21): '+str(1-scipy.stats.norm(30,4).cdf(21))
print 'P(30 < x < 35): '+str(scipy.stats.norm(30,4).cdf(35)-scipy.stats.norm(30,4).cdf(30))

P(x < 40): 0.993790334674
P(x > 21): 0.987775527345
P(30 < x < 35): 0.394350226333


#### Task13: 
The time taken to assemble a car in a certain plant is a random variable having a normal distribution with a mean of 20 hours and a standard deviation of 2 hours. What is the probability that a car can be assembled at this plant in:

a) less than 19.5 hours?

b) between 20 and 22 hours?

In [149]:
#Write your code here
print 'less than 19.5 hours: '+ str(scipy.stats.norm(20,2).cdf(19.5))
print 'between 20 and 22 hours: '+str(scipy.stats.norm(20,2).cdf(22)- scipy.stats.norm(20,2).cdf(20))

less than 19.5 hours: 0.401293674317
between 20 and 22 hours: 0.341344746069


#### Task14:
A manufacturer of metal pistons finds that on average, 12% of his pistons are rejected because they are either oversized or undersized. What is the probability that a batch of 10 pistons will contain

(a) no more than 2 rejects?

(b) at least 2 rejects?

In [150]:
#Write your code here
prob= ((math.factorial(10)/(math.factorial(0)*math.factorial(10))) * (0.12**0) * ((1-0.12)**10) + 
       (math.factorial(10)/(math.factorial(1)*math.factorial(9))) * (0.12**1) * ((1-0.12)**9) +
       (math.factorial(10)/(math.factorial(2)*math.factorial(8))) * (0.12**2) * ((1-0.12)**8))
print 'no more than 2 rejects: ', prob
print 'at least 2 rejects: '+str(1-prob)

no more than 2 rejects:  0.891318206278
at least 2 rejects: 0.108681793722
